import { theme as antdTheme, type ThemeConfig } from "antd"

export function createEcoSignalAntdTheme(isDark: boolean, brand = "var(--es-color-brand)"): ThemeConfig {
    return {
        algorithm: isDark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        token: {
            colorPrimary: brand,
            colorPrimaryHover: "var(--es-color-brand-hover)",
            colorPrimaryActive: "var(--es-color-brand-active)",
            colorInfo: "var(--es-color-info)",
            colorSuccess: "var(--es-color-success)",
            colorWarning: "var(--es-color-warning)",
            colorError: "var(--es-color-danger)",
            colorText: "var(--es-color-text)",
            colorTextSecondary: "var(--es-color-text-secondary)",
            colorTextTertiary: "var(--es-color-text-muted)",
            colorBgBase: "var(--es-color-bg-page)",
            colorBgContainer: "var(--es-color-bg-surface)",
            colorBgElevated: "var(--es-color-bg-elevated)",
            colorBorder: "var(--es-color-border)",
            colorBorderDisabled: "var(--es-color-border)",
            colorBorderSecondary: "var(--es-color-border)",
            controlOutline: "var(--es-color-focus)",
            borderRadius: 6,
            borderRadiusLG: 8,
            borderRadiusSM: 4,
            controlHeight: 32,
            controlHeightLG: 44,
            controlHeightSM: 28,
            fontFamily: "var(--es-font-family-sans)",
            fontSize: 14,
            motionDurationFast: "var(--es-duration-fast)",
            motionDurationMid: "var(--es-duration-normal)",
            motionDurationSlow: "var(--es-duration-slow)",
            boxShadow: "var(--es-shadow-md)",
            boxShadowSecondary: "var(--es-shadow-lg)",
        },
        components: {
            Button: {
                borderRadius: 6,
                borderRadiusLG: 8,
                borderRadiusSM: 4,
                defaultBg: "var(--es-color-bg-surface)",
                defaultBorderColor: "var(--es-color-border)",
                defaultColor: "var(--es-color-text)",
            },
            Drawer: {
                colorBgElevated: "var(--es-color-bg-elevated)",
                paddingLG: 24,
            },
            Input: {
                colorBgContainer: "var(--es-color-bg-subtle)",
                activeBorderColor: brand,
                hoverBorderColor: brand,
                activeShadow: "var(--es-shadow-focus)",
            },
            InputNumber: {
                colorBgContainer: "var(--es-color-bg-subtle)",
                activeBorderColor: brand,
                hoverBorderColor: brand,
                activeShadow: "var(--es-shadow-focus)",
            },
            Select: {
                selectorBg: "var(--es-color-bg-subtle)",
                colorBgContainer: "var(--es-color-bg-subtle)",
                activeBorderColor: brand,
                hoverBorderColor: brand,
                activeOutlineColor: "var(--es-color-focus)",
                optionActiveBg: "var(--es-color-brand-soft)",
                optionSelectedBg: "var(--es-color-brand-soft)",
            },
            DatePicker: {
                colorBgContainer: "var(--es-color-bg-subtle)",
                activeBorderColor: brand,
                hoverBorderColor: brand,
                activeShadow: "var(--es-shadow-focus)",
            },
            Table: {
                headerBg: "var(--es-color-bg-subtle)",
                headerColor: "var(--es-color-text)",
                borderColor: "var(--es-color-border)",
                rowHoverBg: "var(--es-color-brand-soft)",
                stickyScrollBarBg: brand,
            },
            Tooltip: {
                colorBgSpotlight: "var(--es-color-bg-elevated)",
                colorTextLightSolid: "var(--es-color-text)",
            },
        },
    }
}
