"""remove device defaults and seed the standard audio device catalog

Revision ID: f4a6c8e9b012
Revises: e9d84b22adc2
Create Date: 2026-08-30 12:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f4a6c8e9b012"
down_revision: str | None = "e9d84b22adc2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_CATALOG_DATA = {'recorders': [[1, 'µRUDAR-mk2', None, 'Cetacean Research Technology'],
               [2, 'AAD Moored Acoustic Recorder', None, None],
               [3, 'Audiomoth 1.0.0', '1.0.0', 'Open Acoustic Devices'],
               [4, 'AudioMoth 1.1.0', '1.1.0', 'Open Acoustic Devices'],
               [5, 'Audiomoth 1.2.0', '1.2.0', 'Open Acoustic Devices'],
               [6, 'BAR-LT', None, 'Frontier Labs'],
               [7, 'COLMEIA', None, 'Laboratoire Géosciences Océan'],
               [8, 'Curtin Underwater Sound Recorder', None, None],
               [9, 'DR-05', None, 'Tascam'],
               [10, 'DR-07', None, 'Tascam'],
               [11, 'DR-44WL', None, 'Tascam'],
               [12, 'DS-850', None, 'Olympus'],
               [13, 'DSG-ST', None, 'Loggerhead'],
               [14, 'F6', None, 'Zoom'],
               [15, 'H4n', None, 'Zoom'],
               [16, 'H5', None, 'Zoom'],
               [17, 'HYDROMOMAR', None, 'Laboratoire Géosciences Océan'],
               [18, 'LG L70', None, 'LG'],
               [19, 'LS-P4', None, 'Olympus'],
               [20, 'Nomad Jukebox', None, 'Creative'],
               [21, 'PMD 661', None, 'Marantz Professional'],
               [22, 'PMEL AUH/Haruphone', None, None],
               [23, 'Recoti recorder', None, None],
               [24, 'SOLO recorder', None, 'Self-built'],
               [25, 'Song Meter Mini', None, 'Wildlife Acoustics'],
               [26, 'Song Meter SM1', None, 'Wildlife Acoustics'],
               [27, 'Song Meter SM2', None, 'Wildlife Acoustics'],
               [28, 'Song Meter SM2+', None, 'Wildlife Acoustics'],
               [29, 'Song Meter SM2Bat+', None, 'Wildlife Acoustics'],
               [30, 'Song Meter SM3', None, 'Wildlife Acoustics'],
               [31, 'Song Meter SM3 Bat', None, 'Wildlife Acoustics'],
               [32, 'Song Meter SM4', None, 'Wildlife Acoustics'],
               [33, 'Song Meter SM4 Bat FS', None, 'Wildlife Acoustics'],
               [34, 'Soundscape Explorer', None, 'Lunilettronik'],
               [35, 'SoundTrap ST300 HF', None, 'OceanInstruments'],
               [36, 'SoundTrap ST300 STD', None, 'OceanInstruments'],
               [37, 'SoundTrap ST600 STD', None, 'OceanInstruments'],
               [38, 'SWIFT', None, 'The Cornell lab of Ornithology'],
               [39, 'SwiftOne', None, 'The Cornell lab of Ornithology'],
               [40, 'AUSOMS-mini (AQM-102)', None, 'AquaSound'],
               [41, 'MARU', None, 'K. Lisa Yang Center for Conservation Bioacoustics'],
               [42, 'none (cabled hydrophone)', None, ''],
               [43, 'DM-620', None, 'Olympus'],
               [44, 'FR-2LE', None, 'Fostex'],
               [45, 'PMD 660', None, 'Marantz'],
               [46, 'LS-3', None, 'Olympus'],
               [47, 'D240x', None, 'Petterson'],
               [48, 'RFCx Guardian', None, 'Rainforest Connection'],
               [49, 'iPod Touch', None, 'Apple'],
               [50, 'SoundTrap ST400 STD', None, 'OceanInstruments'],
               [51, 'Song Meter Mini Bat', None, 'Wildlife Acoustics'],
               [52, 'Song Meter SM3M', None, 'Wildlife Acoustics'],
               [53, 'SoundTrap ST500 STD', None, 'OceanInstruments'],
               [54, 'Snap', None, 'Loggerhead'],
               [55, 'Snap-Titanium', None, 'Loggerhead'],
               [56, 'LHC Cyclops', None, 'Loggerhead'],
               [57, 'Song Meter SM2M', None, 'Wildlife Acoustics'],
               [58, 'Acoustic Recording Package (ARP)', None, 'Scripps Institution of Oceanography (SIO)'],
               [59,
                'High Frequency Acoustic Recording Package (HARP)',
                None,
                'Scripps Institution of Oceanography (SIO)'],
               [60, 'Providence Node', None, ''],
               [61, 'VHS tape recorder', None, ''],
               [62, 'Oceanpod', None, 'Bunintech'],
               [63, 'EAR I', None, 'Oceanwide Science Institute'],
               [64, 'HTD', None, 'Institute of Deep-sea Science and Engineering Chinese Academy of Sciences'],
               [65, 'OBH', None, 'Institute of Deep-sea Science and Engineering Chinese Academy of Sciences'],
               [66, 'Song Meter Micro', None, 'Wildlife Acoustics'],
               [67, 'AudioMoth-dev 1.2.0', None, 'Open Acoustic Devices'],
               [68, 'D1000X', None, 'Petterson'],
               [69, 'F3', None, 'Zoom'],
               [70, 'F8', None, 'Zoom'],
               [71, 'PCM-M10', None, 'Sony'],
               [72, 'HydroMoth 1.0.0', None, 'Open Acoustic Devices'],
               [73, 'LS-12', None, 'Olympus'],
               [74, 'SoundTrap ST500 HF', None, 'OceanInstruments'],
               [75, 'LS1X', None, 'Loggerhead'],
               [76, 'LS1X-Aluminum', None, 'Loggerhead'],
               [77, 'LS2X', None, 'Loggerhead'],
               [78, 'icListen HF', None, 'Ocean Sonic'],
               [79, 'TCD-5 PRO', None, 'Sony'],
               [80, 'EAR II', None, 'Oceanwide Science Institute'],
               [81, 'custom recorder', None, 'Nortek Méditerranée'],
               [82, 'AURAL M2', None, 'MTE Instruments'],
               [83, 'Shake & Boom', None, 'Raspberry'],
               [84, 'Ares BB+', None, 'Nagra'],
               [85, 'VI', None, 'Nagra'],
               [86, '788T', None, 'Sound Devices'],
               [87, 'NZ DOC ARU', None, ''],
               [88, 'BAR', None, 'Frontier Labs'],
               [89, 'SoundTrap ST4300 HF', None, 'OceanInstruments'],
               [90, 'BUGG', None, ''],
               [91, 'IOS', None, ''],
               [92, 'AMAR', None, ''],
               [93, 'icListen LF', 'Ocen Sonics', ''],
               [94, 'Naxys', '', 'Naxys'],
               [95, 'Naxys Ethernet Hydrophone 02345 TI', '', 'Naxys'],
               [96, 'icListen AF', 'Ocean Sonics', ''],
               [97, 'icListen SC2-ETH', 'Ocean Sonics', ''],
               [98, 'HydroMoth 1.0.1', None, 'Open Acoustic Devices'],
               [99, 'SYLENCE-LP', None, 'RTSYS'],
               [100, 'Solar BAR', None, 'Frontier Labs'],
               [101, 'TMS320C5535', None, 'Texas Instruments'],
               [102, 'Remora', None, 'Loggerhead'],
               [103, 'Pi 4 Model B', None, 'Raspberry'],
               [104, 'LGR-5325', None, ''],
               [105, 'SoundTrap ST600 HF', None, 'OceanInstruments'],
               [106, 'R-1', None, 'Edirol'],
               [108, 'LY-S-01', None, 'LuYin'],
               [109, 'aiWLS-2BS-D/ZY(B)', None, 'Birdsdata'],
               [110, 'MAARU', None, ''],
               [111, 'EcoSnooper', None, 'AviCon']],
 'microphones': [[1, 'AED-2010', None, None, None],
                 [2, 'AquaSound AQH-020D', None, None, None],
                 [3, 'Audio H2a', None, None, None],
                 [4, 'Audiomoth 1.0.0 built-in', None, None, None],
                 [5, 'Audiomoth 1.1.0 built-in', None, None, None],
                 [6, 'Audiomoth 1.2.0 built-in', None, None, None],
                 [7, 'DR-05', None, None, None],
                 [8, 'DR-07 MKII', None, None, None],
                 [9, 'EM172', None, None, None],
                 [10, 'EM-2800A', None, None, None],
                 [11, 'EMY-63M/P', None, None, None],
                 [12, 'FrontierLabs Standard Black Microphone', None, None, None],
                 [13, 'HTI-90-U', None, None, None],
                 [14, 'HTI-94-SSQ', None, None, None],
                 [15, 'HTI-96-MIN', None, None, None],
                 [16, 'ITC-1032', None, None, None],
                 [17, 'JRF', None, None, None],
                 [18, 'Model 600200', None, None, None],
                 [19, 'Pavo', None, None, None],
                 [20, 'Recoti Microphone', None, None, None],
                 [21, 'Sennheiser ME62', None, None, None],
                 [22, 'Sensor Technology SQ26-08', None, None, None],
                 [23, 'SM1 standard microphone', None, None, None],
                 [24, 'SM3 stub microphone (built-in)', None, None, None],
                 [25, 'SM4 stub microphone (built-in)', None, None, None],
                 [26, 'SMM-A1', None, None, None],
                 [27, 'SMM-U1', None, None, None],
                 [28, 'SMM-U2', None, None, None],
                 [29, 'SMO', None, None, None],
                 [30, 'SMX-II (after 2014)', None, None, None],
                 [31, 'SMX-II (before 2014)', None, None, None],
                 [32, 'SMX-U1', None, None, None],
                 [33, 'Song Meter Mini built-in', None, None, None],
                 [34, 'SoundTrap', None, None, None],
                 [35, 'SWIFT', None, None, None],
                 [36, 'AUSOMS-mini stereo microphones', None, None, None],
                 [37, 'icListen HF', None, None, None],
                 [38, 'DM-620 (built-in microphone)', None, None, None],
                 [39, 'DR-44WL (built-in microphone)', None, None, None],
                 [40, 'Sennheiser ME66', None, None, None],
                 [41, 'D240x (built-in microphone)', None, None, None],
                 [42, 'RFCx Guardian (built-in microphone)', '', None, None],
                 [43, 'MICR 020M', None, None, None],
                 [44, 'SMX-US', None, None, None],
                 [45, 'Song Meter Mini Bat (built-in microphone)', None, None, None],
                 [46, 'SoundTrap STD (built-in microphone)', None, None, None],
                 [47, 'SM3M standard', None, None, None],
                 [48, 'SM3M low noise', None, None, None],
                 [49, 'SM2M Standard+Acoustic', None, None, None],
                 [50, 'ARP (built-in microphone)', None, None, None],
                 [51, 'HARP (built-in microphone)', None, None, None],
                 [52, 'DolphinEar', None, None, None],
                 [53, 'HTI-99-HF', '', None, None],
                 [54, 'H0118', '', -153, None],
                 [55, 'SQ26-01', '', None, None],
                 [56, 'H6000', '', None, None],
                 [57, 'H12700', None, None, None],
                 [58, 'Song Meter Micro (built-in microphone)', None, None, None],
                 [59, 'D1000X (built-in microphone)', None, None, None],
                 [60, 'Aquabeat hydrophone', None, None, None],
                 [61, 'HydroMoth 1.0.0 (built-in microphone)', None, None, None],
                 [62, 'EM272', None, None, None],
                 [63, 'Acoustic Microphone Stub (for Mini family)', None, None, None],
                 [64, 'EM 3', None, None, None],
                 [65, 'RESON TC4014', None, None, None],
                 [66, 'RS&BOOM', None, None, None],
                 [67, '4518-003 Accelerometers', None, None, None],
                 [68, '4006 Omnidirectional', None, None, None],
                 [69, 'ST450 Ambisonic', None, None, None],
                 [70, 'NZ DOC ARU (built-in microphone)', None, None, None],
                 [71, 'JRF C-series', None, None, None],
                 [72, 'BUGG (built-in microphone)', 'SPH0641LU4H-1 PDM', None, None],
                 [73, 'IOS (built-in microphone)', '', None, None],
                 [74, 'M36-V35-100', '', None, None],
                 [75, 'icListen LF', '', None, None],
                 [76, 'M8E-51', '', None, None],
                 [77, 'M36-100', '', None, None],
                 [78, 'Naxys (built-in microphone)', '', None, None],
                 [79, 'Naxys Ethernet Hydrophone 02345 TI (built-in microphone)', '', None, None],
                 [80, 'icListen AF', '', None, None],
                 [81, 'icListen SC2-ETH', '', None, None],
                 [82, 'HydroMoth 1.0.1 (built-in microphone)', None, None, None],
                 [83, 'HTI-92-WB', None, None, None],
                 [84, 'GP-1516', None, None, None],
                 [85, 'BII-7016', None, None, None],
                 [86,
                  'custom-made with PTZ disc',
                  'commercial piezoelectric ceramic disc transducer (Ø 35 × 0.47 mm)',
                  None,
                  None],
                 [87,
                  'custom-made with PTZ tube',
                  'commercial P5 Ultrasonic Piezoelectric Ceramic Tube (24×20×20mm; positive pole inside)',
                  None,
                  None],
                 [88, 'LY-S-01 (built-in microphone)', '', None, None],
                 [89, 'C57', '', None, None],
                 [90, 'HD-18X', '', -35, 68],
                 [91, 'MAARU (built-in microphone)', 'MSM321A3729H9CP', -32, 80],
                 [92, 'TRRS mic mono', '', -24, 80]],
 'links': [[1, 22],
           [2, 13],
           [3, 4],
           [4, 4],
           [4, 5],
           [5, 6],
           [5, 86],
           [5, 87],
           [6, 3],
           [6, 12],
           [7, 13],
           [8, 13],
           [8, 15],
           [9, 7],
           [10, 8],
           [11, 39],
           [12, 2],
           [13, 15],
           [13, 53],
           [14, 3],
           [15, 3],
           [16, 3],
           [17, 13],
           [18, 18],
           [20, 15],
           [21, 21],
           [22, 16],
           [23, 20],
           [24, 9],
           [25, 33],
           [26, 23],
           [26, 33],
           [27, 15],
           [27, 30],
           [27, 31],
           [27, 44],
           [28, 15],
           [28, 25],
           [28, 30],
           [28, 31],
           [28, 32],
           [28, 44],
           [28, 53],
           [29, 19],
           [29, 29],
           [29, 30],
           [29, 31],
           [29, 32],
           [29, 44],
           [30, 24],
           [30, 26],
           [31, 27],
           [31, 32],
           [32, 25],
           [33, 15],
           [33, 27],
           [33, 28],
           [33, 32],
           [33, 44],
           [34, 11],
           [35, 15],
           [35, 34],
           [36, 34],
           [36, 46],
           [37, 46],
           [38, 15],
           [38, 35],
           [39, 35],
           [40, 36],
           [41, 14],
           [42, 37],
           [43, 38],
           [46, 40],
           [47, 41],
           [48, 42],
           [49, 43],
           [50, 15],
           [50, 46],
           [51, 33],
           [51, 45],
           [51, 63],
           [52, 15],
           [52, 33],
           [52, 48],
           [53, 15],
           [53, 46],
           [54, 15],
           [56, 15],
           [57, 49],
           [58, 50],
           [59, 51],
           [60, 26],
           [60, 37],
           [61, 52],
           [62, 54],
           [64, 56],
           [65, 57],
           [66, 58],
           [67, 6],
           [67, 9],
           [68, 59],
           [69, 3],
           [69, 71],
           [70, 3],
           [71, 15],
           [71, 60],
           [71, 89],
           [72, 61],
           [73, 62],
           [74, 34],
           [75, 15],
           [76, 15],
           [77, 15],
           [78, 37],
           [79, 64],
           [80, 55],
           [81, 65],
           [82, 15],
           [84, 67],
           [85, 68],
           [86, 69],
           [87, 70],
           [88, 12],
           [89, 15],
           [89, 46],
           [90, 72],
           [91, 73],
           [92, 74],
           [92, 76],
           [92, 77],
           [92, 83],
           [93, 75],
           [94, 78],
           [95, 79],
           [96, 80],
           [97, 81],
           [98, 82],
           [99, 84],
           [100, 12],
           [101, 85],
           [102, 15],
           [103, 15],
           [103, 86],
           [104, 14],
           [105, 34],
           [106, 15],
           [108, 88],
           [109, 90],
           [110, 91],
           [111, 92]]}


def _find_or_insert(connection: sa.Connection, table: str, id_column: str, columns: tuple[str, ...], values: list[object]) -> int:
    predicates = " AND ".join(f"{column} IS NOT DISTINCT FROM :{column}" for column in columns)
    params = dict(zip(columns, values, strict=True))
    existing = connection.execute(
        sa.text(f"SELECT {id_column} FROM {table} WHERE {predicates} ORDER BY {id_column} LIMIT 1"),
        params,
    ).scalar_one_or_none()
    if existing is not None:
        return int(existing)

    placeholders = ", ".join(f":{column}" for column in columns)
    return int(connection.execute(
        sa.text(f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders}) RETURNING {id_column}"),
        params,
    ).scalar_one())


def upgrade() -> None:
    op.drop_column("recorder_microphone", "is_default")
    op.drop_column("camera_lens", "is_default")

    connection = op.get_bind()
    catalog = _CATALOG_DATA
    recorder_ids = {
        int(legacy_id): _find_or_insert(connection, "recorder", "recorder_id", ("name", "version", "brand"), values)
        for legacy_id, *values in catalog["recorders"]
    }
    microphone_ids = {
        int(legacy_id): _find_or_insert(
            connection,
            "microphone",
            "microphone_id",
            ("name", "microphone_element", "sensitivity", "signal_to_noise_ratio"),
            values,
        )
        for legacy_id, *values in catalog["microphones"]
    }
    for recorder_id, microphone_id in catalog["links"]:
        connection.execute(
            sa.text(
                "INSERT INTO recorder_microphone (recorder_id, microphone_id, notes) "
                "VALUES (:recorder_id, :microphone_id, NULL) ON CONFLICT DO NOTHING"
            ),
            {
                "recorder_id": recorder_ids[int(recorder_id)],
                "microphone_id": microphone_ids[int(microphone_id)],
            },
        )


def downgrade() -> None:
    op.add_column("recorder_microphone", sa.Column("is_default", sa.Boolean(), nullable=True, server_default=sa.false()))
    op.add_column("camera_lens", sa.Column("is_default", sa.Boolean(), nullable=True, server_default=sa.false()))
